### ISSUE TITLE
Strategy for handling PRs with edits and new pathways

### ISSUE THREAD

**Issue by khanspers** [wikipathways/sandbox-wp-db#7]
Current idea for the strategy of how to handle incoming PRs for edits and new pathways:

1. PR template will be very simple and just include one sentence, something like "Thank you for your edits / submission. Please allow 48 hours for initial testing and review."
2. Action that runs a set of automated tests (connected interactions, datanodes etc). Writes the results to a config file.
3. Action that adds comments to the PR template based on the results of the tests, for example:

- [x] Interactions are connected
- [x] Datanodes are annotated with database references
- [x] .....
 
There is no editing of the existing body of the template, new lines are simply added. Check-box style would be nice since this is supposed to be human readable. Example: https://github.com/wikipathways/sandbox-wp-db/actions/workflows/on_pr_1.yml 

4. If all tests pass, another action (or the same?) assigns a human reviewer. If ANY test fails, an action alerts the original author.
5. If author submits a new edit based on feedback in the template, the process starts over at 1. 
6. If reviewer decides the pathway needs updates, maybe they manually run a different action that adds additional notes to the template? (unsure about this)
7. If reviewer deems the pathway complete, they manually run another action that  does something similar to on_gpml_change.yml.

**Comment by AlexanderPico** [comment]
Cool. The structure of the GH Action for new PRs might work as a series of steps, each one performing a check, test, or generation of derivative files, along with a chunk of MD text to append to the PR description, e.g., a statement, status, or checkbox.

Groups of steps could be organized into jobs based on the resources needed, e.g., Java or Python packages, clones of other repos, etc. Jobs can be run in parallel or in dependent series, per our needs.

Each job can maintain logic to determine if a reviewer needs to be assigned or not. 

By the end of the action, the PR would include new file attachments and itemized summary for authors and reviewers to see.

**Comment by AlexanderPico** [comment]
Note: The step below from [on_gpml_change.yml](https://github.com/wikipathways/sandbox-wp-db/blob/main/.github/workflows/on_gpml_change.yml) should only occur AFTER review, when PR is accepted and merged. This can be a separate action triggered by PR merges.

* author-list
* homology-conversion
* sync-site-repo-added-modified

**Comment by khanspers** [comment]
Closing. Content is somewhat outdated and better described elsewhere.
